### ISSUE TITLE
[suggestion] maven dependency support

### ISSUE THREAD

**Issue by Grabsky** [LuaLink/LuaLink#5]
I think this can be done using Paper's experimental [loaders](https://docs.papermc.io/paper/dev/getting-started/paper-plugins#loaders) and a configuration file. Could utilize format similar to Spigot's dependency loader within `plugin.yml` file, for example:
```yaml
repositories:
- "https://repo.example.com/maven"
dependencies:
- "com.example:something-api:1.0"
```
Do note this is likely to be useful only for shaded dependencies - mainly libraries - as other plugins' apis will be inaccessible due to [classpath isolation](https://docs.papermc.io/paper/dev/getting-started/paper-plugins#classloading-isolation).
